sudo: false

language: node_js
node_js:
  - stable
  - '6'

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

addons:
  browserstack:
    forcelocal: true
