sudo: false

language: node_js
node_js:
  - stable
  - '6'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_script:
  - npm run serve &
  - npm run serve:browserstack &

script:
  - npm run test
  - pkill node
