sudo: false

language: node_js
node_js:
  - stable
  - '6'

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

addons:
  browserstack:
    forcelocal: true

before_script:
  - BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY
  - npm run serve &

script:
  - npm run test
  - pkill node
